# the rob_ppo config will override default ppo_trainer.yaml

hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

env:
  rollout:
    pipeline_stage_num: 2
  actor:
    model:
      num_action_chunks: 8
      action_dim: 7
  train:
    simulator_type: libero
    max_episode_steps: 512
    reward_coef: 1.0
    step_penalty: 0.001
    only_eval: False
    video_cfg:
      save_video: True
      video_base_dir: /tmp/videos
    num_envs: 16
    seed: 42
    task_suite_name: libero_spatial
    init_params:
      camera_depths: False
      camera_heights: 256
      camera_widths: 256
      camera_names:
        - agentview
        - robot0_eye_in_hand
  disagg_sim:
    enable: False
    nnodes: 1


actor_rollout_ref:
  model:
    override_config:
      sac_enable: True
      flow_sde_enable: True
      flow_sde_noise_level: 0.065
      flow_sde_rollout_noise_scale: 1.0
      flow_sde_train_noise_scale: 1.0
      flow_sde_initial_beta: 1.0
      flow_sde_beta_min: 0.02
      flow_sde_beta_schedule_T: 4000
  actor:
    sac:
      gamma: 0.99
      tau: 1.0
      bc_loss_coef: 0
      initial_alpha: 0
      critic_replay_positive_sample_ratio: 0.5
      actor_replay_positive_sample_ratio: 0.8
      auto_entropy: False
      alpha_type: exp
      alpha_lr: 0.0003
      target_entropy: -64.0
    critic_lr: 0.0001
    critic_weight_decay: 0
    warm_rollout_steps: 23
    critic_warmup_steps: 200
    actor_update_interval: 1
    actor_ema_enabled: true
    actor_ema_decay: 0.95
    replay_pool_save_interval: 500
    num_images_in_input: 1
    traj_mini_batch_size: 16
    replay_pool_single_size: 2000
    replay_pool_save_dir: /tmp/replay_pools
    fsdp_config:
      wrap_policy:
        transformer_layer_cls_to_wrap:
          - PrismaticProjector
          - LlamaDecoderLayer
        min_num_params: 0
      param_offload: False
      optimizer_offload: False
      forward_prefetch: True
      fsdp_size: -1
  rollout:
    mode: async_envloop
    prompt_length: 512
