# Format checks enforced on CI:
# 1. Comments must appear above each field.
# 2. There must be a blank line between each field.
# 3. Inline comments (after a field on the same line) are not allowed.
# 4. Indentation level is respected for nested fields.

_target_: verl.workers.config.DiffusionModelConfig

# path to the huggingface model
path: ~/models/Qwen/Qwen-Image

# path to the huggingface tokenizer. In case it is not the same as path
tokenizer_path: null

# whether to use shared memory for model loading
use_shm: False

# whether to trust remote code.
trust_remote_code: False

# custom chat template for the model
custom_chat_template: null

# whether to use external libs for the model
external_lib: null

# whether to enable gradient checkpointing.
enable_gradient_checkpointing: True

# Set to positive value to enable LoRA (e.g., 32)
lora_rank: 32

# LoRA scaling factor
lora_alpha: 64

# Lora initialization method.
lora_init_weights: gaussian

# Target modules for LoRA adaptation
target_modules: all-linear

# Target parameters for LoRA adaptation
target_parameters: null

# Exclude modules from LoRA adaptation
exclude_modules: null

# Path to pre-trained LoRA adapter to load for continued training
lora_adapter_path: null

# image/video height
height: ${oc.select:actor_rollout_ref.rollout.height,512}

# image/video width
width: ${oc.select:actor_rollout_ref.rollout.width,512}

# inference steps
num_inference_steps: ${oc.select:actor_rollout_ref.rollout.num_inference_steps,10}

# extra configs for algorithm specific features.
extra_configs: ${oc.select:actor_rollout_ref.rollout.extra_configs,{}}
